/**
 * Author:  johnballa
 * Created: 26/04/2021
 */

-- create table for user (staff and admin delineated by boolean is_ values)
CREATE TABLE USER_T (
    USERID      INTEGER     NOT NULL 
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    EMAIL       VARCHAR(50) NOT NULL, 
    FIRSTNAME   VARCHAR(20) NOT NULL, 
    LASTNAME    VARCHAR(20) NOT NULL, 
    PASSWORD    VARCHAR(30) NOT NULL, 
    ADDRESS1    VARCHAR(50),
    ADDRESS2    VARCHAR(50),
    CITY        VARCHAR(15),
    STATELOC    VARCHAR(3),
    POSTCODE    VARCHAR(5),
    PHONE       VARCHAR(12),
    IS_STAFF    BOOLEAN     NOT NULL,
    IS_ADMIN    BOOLEAN     NOT NULL,
    PRIMARY KEY (USERID)
    );

-- insert statements into user table to test database
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('admin@iotbay.com','Admin','Istrator','admin1','123 This Street','This City','NSW','2000','0455667788',TRUE,TRUE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('staff@iotbay.com','Staff','Worker','staff1','234 This Street','This City','NSW','2000','0455667799',TRUE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('1337iotguy@yahoo.com','Bob','Smith','customer1','345 This Street','This City','NSW','2000','0400000000',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test1@gmail.com','firstone','lastone','test1','123 test Street1','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test2@gmail.com','firstone','lastone','test1','123 test Street2','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test3@gmail.com','firstone','lastone','test1','123 test Street3','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test4@gmail.com','firstone','lastone','test1','123 test Street4','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test5@gmail.com','firstone','lastone','test1','123 test Street5','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test6@gmail.com','firstone','lastone','test1','123 test Street6','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test7@gmail.com','firstone','lastone','test1','123 test Street7','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test8@gmail.com','firstone','lastone','test1','123 test Street8','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test9@gmail.com','firstone','lastone','test1','123 test Street9','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test10@gmail.com','firstone','lastone','test1','123 test Street10','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test11@gmail.com','firstone','lastone','test1','123 test Street11','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test12@gmail.com','firstone','lastone','test1','123 test Street12','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test13@gmail.com','firstone','lastone','test1','123 test Street13','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test14@gmail.com','firstone','lastone','test1','123 test Street14','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test15@gmail.com','firstone','lastone','test1','123 test Street15','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test16@gmail.com','firstone','lastone','test1','123 test Street16','Test City','NSW','2000','0455667788',FALSE,FALSE);
INSERT INTO USER_T(EMAIL,FIRSTNAME,LASTNAME,PASSWORD,ADDRESS1,CITY,STATELOC,POSTCODE,PHONE,IS_STAFF,IS_ADMIN) 
    VALUES ('test17@gmail.com','firstone','lastone','test1','123 test Street17','Test City','NSW','2000','0455667788',FALSE,FALSE);

-- create table for user logs, FK to user table
CREATE TABLE USER_LOG_T (
    LOGID           INTEGER     NOT NULL 
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    USERID          INTEGER     NOT NULL,
    CURRENTDATE     DATE        NOT NULL
        DEFAULT CURRENT_DATE,
    CURRENTTIME     TIME        NOT NULL
        DEFAULT CURRENT_TIME,
    LOGEVENT        VARCHAR(20) NOT NULL,
    PRIMARY KEY (LOGID),
    FOREIGN KEY (USERID) REFERENCES USER_T (USERID)
    );

-- insert statements into user log table to test database
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (1,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (1,'2021-04-02','07:00:00','LOGIN');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (1,'2021-04-03','08:00:00','LOGOUT');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (2,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (2,'2021-04-02','07:00:00','LOGIN');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (2,'2021-04-03','08:00:00','LOGOUT');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (3,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (3,'2021-04-02','07:00:00','LOGIN');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (3,'2021-04-03','07:30:00','UPDATE');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (3,'2021-04-04','08:00:00','LOGOUT');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (4,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (5,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (6,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (7,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (8,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (9,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (10,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (11,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (12,'2021-04-01','06:00:00','REGISTER');
INSERT INTO USER_LOG_T(USERID,CURRENTDATE,CURRENTTIME,LOGEVENT)
    VALUES (13,'2021-04-01','06:00:00','REGISTER');

--create table for product
CREATE TABLE PRODUCT_T (
    PRODUCTID   INTEGER     NOT NULL PRIMARY KEY,
    NAME        VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(200)NOT NULL,
    PRICE       FLOAT(10)   NOT NULL,
    STOCK       INTEGER     NOT NULL
    );

INSERT INTO PRODUCT_T VALUES (1,'DHT11','Humidity and Temperature Sensor',4.00,293);
INSERT INTO PRODUCT_T VALUES (2,'DS18B20','1-wire bus Sensor, Raspberry Pi Sensor',2.00,142);
INSERT INTO PRODUCT_T VALUES (3,'BMP180','Barometer Sensor, Raspberry Pi Sensor',6.25,0);
INSERT INTO PRODUCT_T VALUES (4,'RFID-RC522','Inductive RFID Card Reader',5.50,10);
INSERT INTO PRODUCT_T VALUES (5,'Raspberry Pi 7 in. Touchscreen','800x480 pixel, 10 point capacitive touchscreen',75.00,50);

--create table for collection
CREATE TABLE COLLECTION_T (
    COLLECTID   INTEGER     NOT NULL PRIMARY KEY,
    COLLECTNAME VARCHAR(40) NOT NULL
    );

--create table for order
CREATE TABLE ORDER_T (
    ORDERID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USERID INTEGER,
    PRIMARY KEY (ORDERID),
    FOREIGN KEY (USERID) REFERENCES USER_T (USERID)
);

INSERT INTO ORDER_T(USERID) VALUES (1);
INSERT INTO ORDER_T(USERID) VALUES (1);
INSERT INTO ORDER_T(USERID) VALUES (2);
INSERT INTO ORDER_T(USERID) VALUES (NULL);
INSERT INTO ORDER_T(USERID) VALUES (2);
INSERT INTO ORDER_T(USERID) VALUES (NULL);
INSERT INTO ORDER_T(USERID) VALUES (1);
INSERT INTO ORDER_T(USERID) VALUES (2);
INSERT INTO ORDER_T(USERID) VALUES (3);
INSERT INTO ORDER_T(USERID) VALUES (3);
INSERT INTO ORDER_T(USERID) VALUES (NULL);
INSERT INTO ORDER_T(USERID) VALUES (3);
INSERT INTO ORDER_T(USERID) VALUES (2);
INSERT INTO ORDER_T(USERID) VALUES (4);
INSERT INTO ORDER_T(USERID) VALUES (2);
INSERT INTO ORDER_T(USERID) VALUES (2);
INSERT INTO ORDER_T(USERID) VALUES (3);
INSERT INTO ORDER_T(USERID) VALUES (3);
INSERT INTO ORDER_T(USERID) VALUES (1);
INSERT INTO ORDER_T(USERID) VALUES (3);
INSERT INTO ORDER_T(USERID) VALUES (3);
INSERT INTO ORDER_T(USERID) VALUES (3);
INSERT INTO ORDER_T(USERID) VALUES (NULL);
INSERT INTO ORDER_T(USERID) VALUES (3);
INSERT INTO ORDER_T(USERID) VALUES (NULL);

--create table for payment
CREATE TABLE PAYMENT_T (
    PAYID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    PAYMETHOD VARCHAR(20) NOT NULL,
    CCNUMBER INTEGER,
    CCEXP VARCHAR(10),
    CCSECURITY INTEGER,
    PAYEMAIL VARCHAR(50),
    PAYAMOUNT FLOAT,
    PAYDATE VARCHAR(10),
    ORDERID INTEGER,
    PRIMARY KEY (PAYID),
    FOREIGN KEY (ORDERID) REFERENCES ORDER_T (ORDERID)
);

INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 123, '05/21', 777, 'meme@gmail.com', 20, '2021-01-29', 1);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 123, '05/21', 777, '1337iotguy@yahoo.com', 20, '2021-02-17', 9);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 123, '05/21', 777, '1337iotguy@yahoo.com', 96, '2021-04-15', 10);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 123, '05/21', 777, 'meme@gmail.com', 1250, '2021-04-22', 12);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 123, '05/21', 777, '1337iotguy@yahoo.com', 500, '2021-05-7', 17);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 123, '05/21', 777, 'meme@gmail.com', 30, '2021-05-13', 18);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 123, '05/21', 777, 'meme@gmail.com', 20, '2021-05-15', 20);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 21);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 22);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 23);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 5);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 3);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 2);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 10);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 11);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 12);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 15);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 16);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 18);
INSERT INTO PAYMENT_T(PAYMETHOD, CCNUMBER, CCEXP, CCSECURITY, PAYEMAIL, PAYAMOUNT, PAYDATE, ORDERID)
    VALUES ('Credit Card', 321, '05/24', 777, 'samsepi0l@gmail.com', 1500, '2021-05-16', 19);